name: Setup Node .npmrc

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          cache: 'npm'
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lukehedger'

      - name: Print .npmrc file contents
        run: cat /home/runner/work/_temp/.npmrc
